list: $/vpsoft/inventorymanager/models/product/columns.yaml
modelClass: Vpsoft\InventoryManager\Models\Product
title: Products
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'vpsoft/inventorymanager/products/update/:id'
